name: CI-1
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    branches: [master]
env:
  PRJ_NAME: psylla
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: opensuse/tumbleweed:latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Install dependencies
        run: |
          zypper -n --gpg-auto-import-keys in -y \
            ant{,-apache-resolver,-junit} \
            docbook5-xsl-stylesheets \
            git \
            glibc-locale \
            graphviz \
            ivy \
            ivy-local \
            'java-devel>=21' \
            jacoco \
            javacc \
            javapackages-tools \
            'mvn(coneforest:clianthus)' \
            'mvn(jline:jline:1)' \
            'mvn(net.sf.docbook:docbook-xsl-saxon)' \
            'mvn(net.sf.xslthl:xslthl)' \
            'mvn(saxon:saxon)' \
            osc \
            sassc
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config tar.tar.xz.command 'xz -9'
      - name: Build and test
        run: |
          env LANG=C.UTF-8 CLASSPATH=$(build-classpath xerces-j2-xml-apis) JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8 \
            ant -Divy.mode=local build test coverage
