name: CI-1
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    branches: [master]
env:
  PRJ_NAME: psylla
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: opensuse/tumbleweed:latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Build and test
        run: |
#          zypper -n --gpg-auto-import-keys ar -p1 obs://home:urbic:coneforest/openSUSE_Tumbleweed home:urbic:coneforest
#          zypper -n --gpg-auto-import-keys ar -p2 obs://Java:packages/openSUSE_Tumbleweed Java:packages
          zypper -n --gpg-auto-import-keys in -y \
            git
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test GIT
        run: |
          ls -la .
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config tar.tar.xz.command 'xz -9'
#      - name: Configure git to trust the workspace despite the different owner
#        run: |
#          ls -Rla /__w/psylla/psylla/
